### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by jaanos** [marushezz/APPR-2014-15#2]
Poskrbi, da bo zemljevid bolj čitljiv - imena naj ne sežejo čez meje regij, prav tako naj se ne prekrivajo s piko - predpostavljam, da naj bi ta predstavljala Ljubljano (v resnici gre za središče osrednjeslovenske regije). Če želiš narediti piko za Ljubljano, raje naredi
```R
points(14.51, 46.06, pch = 18, cex = 0.5, col = "red")
```
Poskrbi tudi, da bo jasno, kakšne vrednosti zemljevid prikazuje. Lahko dodaš legendo, ali pa pri imenih regij prikažeš še številske vrednosti.

**Comment by jaanos** [comment]
Danes se je očitno zalomilo pri združevanju - ostala si brez uvoza iz XML in risanja grafov, pa še kaj bi se najbrž našlo. Zato bo treba izničiti problematični commit z oznako db6481ccf92a9100ae48edc8ae14a2c8ee7639a8. Svetujem, da slediš naslednjim korakom:

- Shrani in commitaj vse spremembe.
- Poženi Git Bash in se postavi na svoj projekt. Lahko poskusiš v RStudiu v meniju _Tools_ izbrati _Shell..._ - če gre vse po sreči, se bo pognal Git Bash (prepoznaš ga po barvah, pa za imenom imenika piše `(master)`. Če se požene običajna ukazna vrstica, sama poženi Git Bash in se z ukazom `cd` postavi v tvoj projekt.
- Izvedi ukaz
```
git revert db6481ccf92a9100ae48edc8ae14a2c8ee7639a8 -m 2 --no-edit
```
Najbrž boš dobila napako, češ da imaš konflikte. Za imenom imenika bo pisalo `(master|REVERTING)`.

- Sedaj greš v RStudio, kjer lahko v zavihku _Git_ desno zgoraj (ali pa v oknu, kjer delaš commit) vidiš, kakšno je stanje. Potrebno bo odpraviti konflikte, ki so sedaj nastali v poročilu (morda še kje, če si še kaj drugega spreminjala). Prepričaj se, da ti program deluje (počisti delovno okolje in poženi `projekt.r`); prepričaj se, da je v `uvoz.r` tudi uvoz iz XML in risanje grafa.
- Ko odpraviš konflikte v poročilu, se prepričaj, da ga prevede ter da izgleda tako, kot mora.
- Pobriši datoteki `.RData` in `porocilo/porocilo.synctex.gz`, ki sta se spet pojavili.
- Obkljukaj vse ponujene datoteke ter naredi commit in push.

To bi ti moralo odpraviti težave, hkrati pa ohraniti tvoje zadnje popravke. Če kakšno stvar pogrešaš, lahko vedno pogledaš v zgodovino (v RStudiu ali GitHubu).

Naslednjič na faksu (svetujem, da čimprej) naredi pull, da dobiš te spremembe. Če imaš tam kakšne necomittane spremembe in bi jih rada zavrgla, lahko v RStudiu spremenjene datoteke označiš (ne da bi jih obkljukala) in klikneš na gumb _Revert_, da ti zavrže spremembe, preden lahko narediš pull.

**Comment by marushezz** [comment]
Ko dam compile PDF mi vrne Issues: 1 badbox.. kako naj to odpravim? 
Najlepša hvala

**Comment by jaanos** [comment]
Poglej pod _Issues_, v kateri vrstici se ti pojavi badbox. Če je to zaradi grafa ali tabele, to načeloma ni problem. Če se izkaže, da tam kakšna beseda štrli čez desni rob besedila, pomeni, da je LaTeX ni znal deliti - lahko sama poveš, kje jo naj deli, tako da na ustrezno mesto vstaviš `\-`.

**Comment by marushezz** [comment]
V issues piše da je url predlog, probala sem z \- pa tudi z \usepackage[breaklinks=true,pdfborder={0 0 0},bookmarksopen]{hyperref} in podobnimi ukazi, pa mi problema še vedno ni uspelo razrešiti.. je možna še kakšna rešitev?

**Comment by jaanos** [comment]
Naloži trenutno verzijo na GitHub, pa bom pogledal, kaj bi se dalo narediti. Sicer pa če ti samo en spletni naslov štrli čez rob, to ni tak problem.

**Comment by jaanos** [comment]
Očitno ni kaj dosti za narediti glede badboxov. Sicer pa trik z `\-` deluje samo v navadnem besedilu - v URL-jih tega ne uporabljaj, ker ti bo ta znaka tudi dejansko prikazalo.

**Comment by marushezz** [comment]
na gitbashu sem "potegnila" staro verzijo porocila in vizualizacije... mislm da je sedaj vse kot je bilo pred konflikti...Ali še kje kaj popravim?

**Comment by jaanos** [comment]
Sedaj je v redu, program deluje in poročilo se prevede, tako da sem popravil povezavo na repozitoriju za predstavitve. Poglej edino še komentar, ki sem ti ga dal pri commitu 646af2d494c8f5c342050e162982a8ebc8450393.

Če boš pred predstavitvijo še kaj spreminjala program oziroma poročilo, sledi navodilom na repozitoriju za predstavitve.
