### ISSUE TITLE
četrta faza

### ISSUE THREAD

**Issue by marushezz** [marushezz/APPR-2014-15#3]
Spoštovani,
v četrti fazi sem naredila primerjavo BDP glede na število prebivalcev v Sloveniji in opazila da je od let 2000-2008 raslo prebivalstvo in BDP po 2008 pa je BDP začel padati prebivalstvo pa je še vedno raslo.
Zanima me, če imate še kakšno idejo kaj naj naredim oz. izboljšam.. Je sploh možno narediti napoved zaradi te spremembe podatkov?
Hvala za pomoč.

**Comment by jaanos** [comment]
Ena stvar, ki jo lahko pogledaš, je hitrost rasti prebivalstva (torej prirastek glede na prejšnje leto) - morda se bo pa tukaj kaj poznalo (mogoče z nekolikšno zamudo).

Če prebivalstvo ves čas raste, lahko seveda delaš napoved števila prebivalcev skozi čas (torej ne glede na BDP ali druge spremenljivke). Seveda lahko poskusiš najti kakšne korelacije med ostalimi podatki, ki jih imaš na voljo, ali pa še kakšne podatke dodatno uvoziš.

**Comment by marushezz** [comment]
Naredila sem ločena modela za prebivalstvo in BDP  v prihodnosti.. sta v redu ali kaj spremenim? Zanima me še nekaj glede poročila.. v compile pdf mi še vedno napiše da imam 1 badbox vendar mi poročilo prevede ali moram kaj spremeniti še v poročilu ali bo v redu?

**Comment by jaanos** [comment]
Najprej naj opozorim, da funkcija `forecast` ni nikjer definirana - najbrž si uporabila funkcijo iz istoimenske knjižnice, ki jo bo tako treba nekje uvoziti.

Pri vsakem modelu v poročilu navedi, kako si ga dobila (torej katero funkcijo si uporabila). Modeli, pridobljeni s funkcijo `forecast`, kažejo tudi negotovost oziroma interval, v katerem naj bi prikazana spremenljivka ležala ob določenem času z določeno verjetnostjo - privzeto sta prikazani verjetnosti 80% in 95%. Iz grafov je videti, da je negotovost za BDP veliko večja kot za število prebivalcev. To omeni v poročilu, ter pojasni, kaj katero območje kaže - lahko seveda tudi spremeniš verjetnosti tako, da jih podaš funkciji `forecast` s parametrom `level`.

Badboxi niso večji problem - lahko pa vseeno pogledaš, kje se nahajajo, saj lahko nastanejo, ker besedilo štrli čez desni rob. V veliki meri se temu izogneš, če za vejicami in pikami postavljaš presledke (kakor se tudi sicer spodobi); včasih pa LaTeX ne zna deliti besed s šumniki in je treba vstaviti `\-` na mesta, kjer lahko deli.

**Comment by marushezz** [comment]
Sedaj sem popravila, kar ste mi svetovali. Glede badboxov sem se jih poskušala znebiti pa nikakor ne uspe. Naredila pa sem še primerjavo deleža BDP in prebivalstva po regijah, ter primerjavo BDP in dolga.
Morda najdete še kje kakšne pomankljivosti, da jih popravim pred oddajo projekta?
Najlepša hvala.

**Comment by jaanos** [comment]
Trenutno ti program riše dva grafa v RStudiu - če ju ne misliš vključiti v poročilo, ju odstrani ali zakomentiraj. Poleg tega način prikaza primerjave deleža BDP in prebivalstva ni najbolj primeren, saj ti podana urejenost regij nič ne pove. Tukaj tako raje uporabi stolpčni graf, regije pa uredi po enem od prikazanih podatkov. Tak črtni graf lahko potem uporabiš pri primerjavi bruto dodane vrednosti in dolga skozi čas.

Ko boš imela končno verzijo na GitHubu, odpri issue na [repozitoriju za zagovore](https://github.com/jaanos/APPR-2014-15-zagovori) ter se s profesorjem domeni za termin zagovora.

**Comment by jaanos** [comment]
Še glede badboxov: nekaj se jih lahko znebiš tako, da vrstic ne končaš z `\\`, ampak enostavno pustiš prazno vrstico pred naslednjim odstavkom. Kot sem že omenil, pazi tudi, da za pikami in vejicami postavljaš presledke. Nekaj badboxov bo še ostalo na račun grafov in URL-jev, ampak ti niso problem.

**Comment by jaanos** [comment]
Sem dodal povezavo na trenutno verzijo. Opomnil bi edino še, da bi bilo potrebno pri primerjavi deleža BDP in prebivalstva pod stolpci imeti imena regij.

Če boš torej še kaj spreminjala, odpri nov issue na repozitoriju za zagovore, ali pa ponovno odpri starega.

**Comment by marushezz** [comment]
Najlepša hvala.
Sem poskusila dodati imena regij vendar so imena predolga in ne izpiše vseh. Je bolje da pustim, kot je ali imate kakšen drug predlog?
